"""Add receipt fields to User

Revision ID: 612ca61c84a5
Revises: 4fbb649ac4e2
Create Date: 2025-06-08 00:17:06.450282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612ca61c84a5'
down_revision = '4fbb649ac4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('receipt_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('receipt_uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('receipt_uploaded_at')
        batch_op.drop_column('receipt_status')
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###
